version: "3.8"

services:
  db:
    image: postgres:16-alpine
    container_name: shared_db
    environment:
      POSTGRES_DB: shared_db
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-supersecretpgpassword}
      POSTGRES_HOST_AUTH_METHOD: trust
    env_file:
      - .env
    networks:
      - app-network
    volumes:
      - shared_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_user -d shared_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth_microservice
    env_file:
      - .env
    networks:
      - app-network
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://db_user:${DB_PASSWORD:-supersecretpgpassword}@db:5432/shared_db
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  shared_db_data:
